# Generated by Django 6.0.4 on 2026-04-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0004_service_carimage_favorite_order_orderitem_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CN', 'Отказ'), ('BK', 'Бронь'), ('AR', 'В архиве')], default='BK', max_length=8, verbose_name='Статус'),
        ),
    ]
