# Generated by Django 6.0.4 on 2026-04-21 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0005_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название пакета')),
                ('package_type', models.CharField(choices=[('WINTER', '❄️ Зимний пакет'), ('SPORT', '🏎️ Спортивный пакет'), ('PREMIUM', '👑 Премиум пакет'), ('FAMILY', '👨\u200d👩\u200d👧\u200d👦 Семейный пакет'), ('SAFETY', '🛡️ Пакет безопасности'), ('TECH', '📱 Технологический пакет')], max_length=20, verbose_name='Тип пакета')),
                ('description', models.TextField(help_text='Что входит в пакет', verbose_name='Описание пакета')),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доплата за пакет (₽)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Пакет оборудования',
                'verbose_name_plural': 'Пакеты оборудования',
                'ordering': ['package_type', 'additional_price'],
            },
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('BK', 'Бронь'), ('AR', 'В архиве')], default='BK', max_length=8, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='car',
            name='equipment_packages',
            field=models.ManyToManyField(blank=True, help_text='Выберите пакеты оборудования, доступные для этого автомобиля', to='avto.equipmentpackage', verbose_name='Пакеты оборудования'),
        ),
        migrations.CreateModel(
            name='CarEquipmentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Доступен для заказа'), ('INSTALLED', 'Установлен'), ('PLANNED', 'Запланирован'), ('UNAVAILABLE', 'Недоступен')], default='AVAILABLE', max_length=20, verbose_name='Статус установки')),
                ('installed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата установки')),
                ('notes', models.TextField(blank=True, help_text='Особенности установки, комплектация и т.д.', verbose_name='Примечания')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_packages', to='avto.car', verbose_name='Автомобиль')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_cars', to='avto.equipmentpackage', verbose_name='Пакет оборудования')),
            ],
            options={
                'verbose_name': 'Пакет на автомобиле',
                'verbose_name_plural': 'Пакеты на автомобилях',
                'unique_together': {('car', 'package')},
            },
        ),
    ]
