# Generated by Django 6.0.4 on 2026-05-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0008_alter_car_equipment_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='document',
            field=models.FileField(blank=True, help_text='ПТС, сервисная книжка или другой документ', null=True, upload_to='car_documents/', verbose_name='Документ на автомобиль'),
        ),
        migrations.AddField(
            model_name='car',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ссылка на YouTube или другой видеохостинг', null=True, verbose_name='Ссылка на видеообзор'),
        ),
    ]
