# Generated by Django 6.0.6 on 2026-06-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0011_alter_car_id_alter_carequipmentpackage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='stock',
            field=models.PositiveIntegerField(default=10, verbose_name='Свободные места'),
        ),
    ]
